[package]
name = "assignment_11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.13"
async-std = "1.9.0"
log = "0.4.14"
env_logger = "0.9.0"